

export const PropertiesData = [
  {
    id: 1,
    type: "Apartment",
    location: "Downtown Lagos",
    price: 1500,
    bedrooms: 2,
    bathrooms: 2,
    size: "1200 sqft",
    image:
      "https://i.ibb.co/Lnp0Pcq/apartment-building-city-with-copy-space-23-2148814165.jpg",
    features: ["Balcony", "24/7 Security", "Swimming Pool", "Gym",],
  },
  {
    id: 2,
    type: "House",
    location: "Lekki Phase 1, Lagos",
    price: 3000,
    bedrooms: 4,
    bathrooms: 3,
    size: "3000 sqft",
    image: "https://i.ibb.co/5s72Lt4/image.png",
    features: ["Private Garden", "Garage", "Gated Community"],
  },
  {
    id: 3,
    type: "Condo",
    location: "Victoria Island, Lagos",
    price: 2500,
    bedrooms: 3,
    bathrooms: 2,
    size: "1500 sqft",
    image: "https://i.ibb.co/0YM0jcv/image.png",
    features: ["Sea View", "Roof Terrace", "Elevator"],
  },
  {
    id: 4,
    type: "Townhouse",
    location: "Ikeja GRA, Lagos",
    price: 1800,
    bedrooms: 3,
    bathrooms: 3,
    size: "2000 sqft",
    image: "https://i.ibb.co/qFC8Tjp/image.png",
    features: ["Modern Kitchen", "Parking Space", "Playground"],
  },
  {
    id: 5,
    type: "Villa",
    location: "Banana Island, Lagos",
    price: 10000,
    bedrooms: 6,
    bathrooms: 6,
    size: "8000 sqft",
    image: "https://i.ibb.co/rMRNmSs/image.png",
    features: ["Private Pool", "Home Theater", "Sauna"],
  },
  {
    id: 6,
    type: "Studio Apartment",
    location: "Surulere, Lagos",
    price: 800,
    bedrooms: 1,
    bathrooms: 1,
    size: "600 sqft",
    image: "https://i.ibb.co/6ysM6yc/image.png",
    features: ["Fully Furnished", "Air Conditioning", "Wi-Fi"],
  },
  {
    id: 7,
    type: "Penthouse",
    location: "Eko Atlantic, Lagos",
    price: 7000,
    bedrooms: 5,
    bathrooms: 4,
    size: "4000 sqft",
    image: "https://i.ibb.co/4MN6hDC/image.png",
    features: ["Skyline View", "Jacuzzi", "Bar Area"],
  },
  {
    id: 8,
    type: "Bungalow",
    location: "Ajah, Lagos",
    price: 1200,
    bedrooms: 3,
    bathrooms: 2,
    size: "2500 sqft",
    image: "https://i.ibb.co/B4VqGNM/image.png",
    features: ["Solar Panels", "Spacious Backyard", "Carport"],
  },
  {
    id: 9,
    type: "Cottage",
    location: "Ibadan, Oyo State",
    price: 900,
    bedrooms: 2,
    bathrooms: 2,
    size: "1800 sqft",
    image: "https://i.ibb.co/mzzcKxf/wood-mansion-pine-forest-266732-25480.jpg",
    features: ["Fireplace", "Outdoor Patio", "Nearby Hiking Trails"],
  },
  {
    id: 10,
    type: "Duplex",
    location: "Abuja City Center",
    price: 3500,
    bedrooms: 4,
    bathrooms: 4,
    size: "3200 sqft",
    image: "https://i.ibb.co/Wc35nwd/image.png",
    features: ["Two Living Rooms", "Guest Room", "CCTV Security"],
  },
  {
    id: 11,
    type: "Farmhouse",
    location: "Abeokuta, Ogun State",
    price: 2000,
    bedrooms: 3,
    bathrooms: 2,
    size: "5000 sqft",
    image: "https://i.ibb.co/jVVt476/image.png",
    features: ["Farm Land", "Barn", "Fruit Trees"],
  },
  {
    id: 12,
    type: "Office Space",
    location: "Central Business District, Abuja",
    price: 5000,
    bedrooms: 0,
    bathrooms: 2,
    size: "2000 sqft",
    image: "https://i.ibb.co/6gRkRR6/image.png",
    features: ["Conference Room", "High-Speed Internet", "Furnished"],
  },
  {
    id: 13,
    type: "Retail Shop",
    location: "Wuse Market, Abuja",
    price: 1000,
    bedrooms: 0,
    bathrooms: 1,
    size: "800 sqft",
    image: "https://i.ibb.co/sRf4swn/image.png",
    features: ["Display Shelves", "Customer Parking", "Prime Location"],
  },
  {
    id: 14,
    type: "Warehouse",
    location: "Apapa, Lagos",
    price: 8000,
    bedrooms: 0,
    bathrooms: 1,
    size: "15000 sqft",
    image: "https://i.ibb.co/MnqfXy4/image.png",
    features: ["Loading Dock", "24-Hour Access", "Security Patrol"],
  },
  {
    id: 15,
    type: "Luxury Mansion",
    location: "Asokoro, Abuja",
    price: 15000,
    bedrooms: 8,
    bathrooms: 8,
    size: "12000 sqft",
    image: "https://i.ibb.co/zPsQ7Nx/image.png",
    features: ["Helipad", "Wine Cellar", "Private Cinema"],
  },
];
